variant: flatcar
version: 1.0.0
passwd:
  users:
  - name: core
    - ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMtujVE0Ye22HXdMMGR2h0obMqEge7CRWIEKrQC3dhn1 rjallen@2015-macos-1013.local"
  - name: rjallen
    password_hash: "$6$43y3tkl..."
    - ssh_authorized_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDxoIjMTkmm+GRgoFAT7VT84sgtJONuNLyt6YgSeZJxS7HuZmuFTo9muFXVNLr58FBZOBhly4GdOb/dyuOjTuvxvvDAcbp38PJbRJud0IVPHNX7+qoKTwsh+HkPCE8Js5KYiNbvCXj006zcFHVbHcvQtLK3snKSBTy1rPxc9twhSm0emIpuGe3xbn2Il7TYnUtUyPGbzkvxmkhh/vD/2/Rjy/VgxmnUl9NNmpy+i3iWBOzvbpZujEwQyB3IqgqjuZSl0T8daDYKOKyA1DSBDIUc7ZEr5vNRPhM0EZwgc846kvCn3a8HBRb4z8cMvBoziATyTTxmHCdD6aj4Y5AbmV6MORPUYCc1em3uSskmQzOBWE/PmTPBZozDvT4IHkCkJAD+jY4AqeaH548wVlwIxwxDLLSkQrB0Mo6CsiHMWnGjJXpA1kGBnfNYBh3V0P9Z3hURzkaJXUb27RaoDSfBJ4qH/UkL7VEwyQhlD7DaShbxlpqr5sSqHH2XOYrwFhE7fYM= rjallen@Rjs-MacBook-old.local"
    home_dir: /home/rjallen
    groups:
      - wheel
      - plugdev
      - sudo
      - wheel
      - docker
    shell: /bin/zsh

storage:
  directories:
    - path: /etc/systemd/system
      user:
        id: 0
        name: root
      group:
        id: 0
        name: wheel
      mode: 0644
    - path: /etc/systemd/user
      user:
        id: 0
        name: root
      group:
        id: 0
        name: wheel
      mode: 0644
  files:
    - path: /etc/hosts
      contents:
        inline: 127.0.0.1 flatcar-inst
      mode: 0644
      user:
        id: 0
      group:
        id: 501    - device: /dev/disk/by-partlabel/HOME
      format: btrfs
      wipe_filesystem: true
      label: HOME
  filesystems:
    - device: /dev/disk/by-partlabel/ROOT
      format: btrfs
      wipe_filesystem: true
      label: ROOT
    - device: /dev/disk/by-partlabel/HOME
      format: btrfs
      wipe_filesystem: true
      label: HOME
    - device: /dev/disk/by-partlabel/SWAP
      format: swap
      wipe_filesystem: true
      label: SWAP
    - device: /dev/disk/by-partlabel/OPT
      format: btrfs
      wipe_filesystem: true
      label: OPT







